### ISSUE TITLE
Doesn't support connectivity for Cisco IOS XE

### ISSUE THREAD

**Issue by saklar13** [QualiSystems/Cisco-IOS-Router-Shell-2G#6]
Failed with error 
```
CloudShellAPIError: CloudShell API error 100: Add Vlan 3 configuration failed.
Add Vlan configuration details:
. Add Vlan 3 configuration failed.
Add Vlan configuration details:
```

CloudShell log
```
2018-11-27 03:07:20,654 [INFO]: QS.Cisco-IOS-simulator1-2.Thread-12 driver - ApplyConnectivityChanges Start applying connectivity changes, request is: 
{"driverRequest":{"actions":[{"connectionId":"bd9a8b57-dd37-4d7b-8aa4-893b44b65a4d",
"connectionParams":{"vlanId":"3","mode":"Access","vlanServiceAttributes":[{"attributeName":"Allocation Ranges","attributeValue":"2-4094","type":"vlanServiceAttribute"},
{"attributeName":"Isolation Level","attributeValue":"Exclusive","type":"vlanServiceAttribute"},
{"attributeName":"Access Mode","attributeValue":"Access","type":"vlanServiceAttribute"},
{"attributeName":"VLAN ID","attributeValue":"","type":"vlanServiceAttribute"},
{"attributeName":"Pool Name","attributeValue":"","type":"vlanServiceAttribute"},
{"attributeName":"Virtual Network","attributeValue":"","type":"vlanServiceAttribute"},
{"attributeName":"Default VLAN","attributeValue":"","type":"vlanServiceAttribute"},
{"attributeName":"QnQ","attributeValue":"False","type":"vlanServiceAttribute"},
{"attributeName":"CTag","attributeValue":"","type":"vlanServiceAttribute"}],
"type":"setVlanParameter"},
"connectorAttributes":[{"attributeName":"Selected Network","attributeValue":"3","type":"connectorAttribute"}],
"actionId":"bd9a8b57-dd37-4d7b-8aa4-893b44b65a4d_04a20c20-ced6-429a-8e2c-7ce5bfeaf326",
"actionTarget":{"fullName":"Cisco-IOS-simulator1-2/Chassis 0/Module 6/GigabitEthernet2",
"fullAddress":"192.168.42.155/CH0/M6/P2","type":"actionTarget"},
"customActionAttributes":[],"type":"setVlan"},
{"connectionId":"bd9a8b57-dd37-4d7b-8aa4-893b44b65a4d","connectionParams":
{"vlanId":"3","mode":"Access","vlanServiceAttributes":[{"attributeName":"Allocation Ranges","attributeValue":"2-4094","type":"vlanServiceAttribute"},
{"attributeName":"Isolation Level","attributeValue":"Exclusive","type":"vlanServiceAttribute"},
{"attributeName":"Access Mode","attributeValue":"Access","type":"vlanServiceAttribute"},
{"attributeName":"VLAN ID","attributeValue":"","type":"vlanServiceAttribute"},
{"attributeName":"Pool Name","attributeValue":"","type":"vlanServiceAttribute"},
{"attributeName":"Virtual Network","attributeValue":"","type":"vlanServiceAttribute"},
{"attributeName":"Default VLAN","attributeValue":"","type":"vlanServiceAttribute"},
{"attributeName":"QnQ","attributeValue":"False","type":"vlanServiceAttribute"},
{"attributeName":"CTag","attributeValue":"","type":"vlanServiceAttribute"}],"type":"setVlanParameter"},
"connectorAttributes":[{"attributeName":"Selected Network","attributeValue":"3","type":"connectorAttribute"}],
"actionId":"bd9a8b57-dd37-4d7b-8aa4-893b44b65a4d_64602e70-7e9e-44aa-b6cf-7377a9ddcb20",
"actionTarget":{"fullName":"Cisco-IOS-simulator1-2/Chassis 0/Module 6/GigabitEthernet1","fullAddress":"192.168.42.155/CH0/M6/P1","type":"actionTarget"},
"customActionAttributes":[],"type":"setVlan"}]}}
2018-11-27 03:07:20,664 [INFO]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - apply_connectivity_changes Action: 
2018-11-27 03:07:20,667 [INFO]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - apply_connectivity_changes Action: 
2018-11-27 03:07:20,670 [INFO]: QS.Cisco-IOS-simulator1-2.Thread-12 cisco_add_vlan_flow - execute_flow         Add VLAN(s) 3 configuration started
2018-11-27 03:07:20,671 [INFO]: QS.Cisco-IOS-simulator1-2.Thread-12 cisco_add_vlan_flow - execute_flow         Add VLAN(s) 3 configuration started
2018-11-27 03:07:20,710 [DEBUG]: QS.Cisco-IOS-simulator1-2.Thread-12 session_pool_manager - _get_from_pool       getting session from the pool
2018-11-27 03:07:20,812 [DEBUG]: QS.Cisco-IOS-simulator1-2.Thread-12 expect_session - hardware_expect      Command: 
2018-11-27 03:07:20,924 [DEBUG]: QS.Cisco-IOS-simulator1-2.Thread-12 expect_session - hardware_expect      
2018-11-27 03:07:20,924 [DEBUG]: QS.Cisco-IOS-simulator1-2.Thread-12 expect_session - hardware_expect      CSR1Kv(config)#
2018-11-27 03:07:21,026 [INFO]: QS.Cisco-IOS-simulator1-2.Thread-12 iface_actions - get_port_name        Interface name validation OK, portname = GigabitEthernet2
2018-11-27 03:07:21,128 [DEBUG]: QS.Cisco-IOS-simulator1-2.Thread-12 expect_session - hardware_expect      Command: vlan 3
2018-11-27 03:07:21,242 [DEBUG]: QS.Cisco-IOS-simulator1-2.Thread-12 expect_session - hardware_expect      vlan 3
2018-11-27 03:07:21,242 [DEBUG]: QS.Cisco-IOS-simulator1-2.Thread-12 expect_session - hardware_expect                          ^
2018-11-27 03:07:21,242 [DEBUG]: QS.Cisco-IOS-simulator1-2.Thread-12 expect_session - hardware_expect      % Invalid input detected at '^' marker.
2018-11-27 03:07:21,242 [DEBUG]: QS.Cisco-IOS-simulator1-2.Thread-12 expect_session - hardware_expect      
2018-11-27 03:07:21,242 [DEBUG]: QS.Cisco-IOS-simulator1-2.Thread-12 expect_session - hardware_expect      CSR1Kv(config)#
2018-11-27 03:07:21,246 [DEBUG]: QS.Cisco-IOS-simulator1-2.Thread-12 session_pool_manager - return_session       Return session to the pool
2018-11-27 03:07:21,250 [ERROR]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - add_vlan             Traceback (most recent call last):
2018-11-27 03:07:21,250 [ERROR]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - add_vlan               File "C:\ProgramData\QualiSystems\venv\Cisco_IOS_Router_2G_2_12\lib\site-packages\cloudshell\devices\runners\connectivity_runner.py", line 215, in add_vlan
2018-11-27 03:07:21,250 [ERROR]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - add_vlan                 c_tag=c_tag)
2018-11-27 03:07:21,250 [ERROR]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - add_vlan               File "C:\ProgramData\QualiSystems\venv\Cisco_IOS_Router_2G_2_12\lib\site-packages\cloudshell\networking\cisco\flows\cisco_add_vlan_flow.py", line 36, in execute_flow
2018-11-27 03:07:21,250 [ERROR]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - add_vlan                 vlan_actions.create_vlan(vlan_range)
2018-11-27 03:07:21,250 [ERROR]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - add_vlan               File "C:\ProgramData\QualiSystems\venv\Cisco_IOS_Router_2G_2_12\lib\site-packages\cloudshell\networking\cisco\command_actions\add_remove_vlan_actions.py", line 49, in create_vlan
2018-11-27 03:07:21,250 [ERROR]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - add_vlan                 error_map=error_map).execute_command(vlan_id=vlan_range)
2018-11-27 03:07:21,250 [ERROR]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - add_vlan               File "C:\ProgramData\QualiSystems\venv\Cisco_IOS_Router_2G_2_12\lib\site-packages\cloudshell\cli\command_template\command_template_executor.py", line 49, in execute_command
2018-11-27 03:07:21,250 [ERROR]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - add_vlan                 **self.optional_kwargs)
2018-11-27 03:07:21,250 [ERROR]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - add_vlan               File "C:\ProgramData\QualiSystems\venv\Cisco_IOS_Router_2G_2_12\lib\site-packages\cloudshell\cli\cli_service_impl.py", line 88, in send_command
2018-11-27 03:07:21,250 [ERROR]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - add_vlan                 error_map=error_map, logger=logger, *args, **kwargs)
2018-11-27 03:07:21,250 [ERROR]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - add_vlan               File "C:\ProgramData\QualiSystems\venv\Cisco_IOS_Router_2G_2_12\lib\site-packages\cloudshell\cli\session\expect_session.py", line 260, in hardware_expect
2018-11-27 03:07:21,250 [ERROR]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - add_vlan                 'Session returned \'{}\''.format(error_map[error_string]))
2018-11-27 03:07:21,250 [ERROR]: QS.Cisco-IOS-simulator1-2.Thread-12 connectivity_runner - add_vlan             CommandExecutionException: ('SSHSession', "Session returned '('CONFIGURE_VLAN', 'Error')'")
```

**Comment by Costya-Y** [comment]
Fixed, and will be published in the upcoming release
